---
#
# Ansible managed
#
repository:
  description: Install and configure automatic package updates on your system.
  homepage: https://buluma.github.io/
  topics: autoupdate, security, system, ansible, molecule, playbook
